### PR TITLE
feat(virtualhub): add interface for internet and private intent based routing

### PR DESCRIPTION
**Pull request by b0bu**
# Overview/summary

This PR is in Draft and will be refined in the coming days. 

Newly released intent based routing capabilities enabled vhub to vhub inter-region traffic filtering. Amoung many other traffic flows. Once enabled full mesh traffic filtering between regions is possible. 

## This PR fixes/adds/changes/removes

Adds toggles to configure a intent based routing in vwan security configuration.

Currently in testing
```hcl
intent_based_routing          = optional(bool, false)
intent_based_routing_next_hop = optional(string, "")
```
But might propose depending how testing goes
```hcl
intent_based_routing = optional(object({
     next_hop_firewall = optional(string, "")
}), {})
```

### Breaking changes

No breaking changes

## Testing evidence

Please provide testing evidence to show that your Pull Request works/fixes as described and documented above.

## As part of this pull request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [ ] Run and `make fmt` & `make docs` to format your code and update documentation.
- [ ] Created unit and deployment tests and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by b0bu** [comment]
> Thanks @b0bu for the draft PR.
> 
> Routing intent is indeed a much needed feature that im sure glad to see arrive for VWAN.
> 
> However, I believe this is a hub based setting, as its a child resource of the hub from an ARM perspective, therefore I'm not sure it makes sense to be configured in this module, as this module doesn't configure the hub. It only configures spoke connections to connect to a hub.
> 
> And as routing intent is designed to only define a hub based routing intent and not on a per connection basis, I'm not sure its best placed in this module, and would be better suited in a virtual wan hub side module.
> 
> Thoughts?
> 
> cc: @matt-FFFFFF

@jtracey93  Absolutely. In my test case I was creating a vnet in the sanbox subscription but updating the vhub in the connectivity subscirption which is obviously wrong because the subscirption have different archetypes but would be fine if I were spining up a vnet and firewall in the sandbox for testing. I don't see where `azapi_resource` cares about the subscirption_id so I'm not sure would could even enforce that in code if you wanted to make sure the firewall was in the subscirption you were creating / updating. 

The previous block in that file touches `Microsoft.Network/virtualHubs` which configured secure internet and private traffic at the vhub route table. 

```hcl
# azapi_resource.vhubconnection creates a virtual wan hub connection between the spoke and the supplied vwan hub.
resource "azapi_resource" "vhubconnection" {
  for_each  = { for k, v in var.virtual_networks : k => v if v.vwan_connection_enabled }
  type      = "Microsoft.Network/virtualHubs/hubVirtualNetworkConnections@2021-08-01"
  parent_id = each.value.vwan_hub_resource_id
```
Where `vwan_security_configuration` secure private and public traffic is a toggle on a per vnet / vhc basis so it makes sense for it to be here, per vnet and in the `virtual_network` object. Since this call to the intent resource feels a bit more like a global change for all vnets it might make sense to move the config outside of the `virtual_network` block and into its own `virtual_hub` object , configured per "connectivity" subscirption or in which ever sub firewalls are installed.  

Happy to move my changes to a virutalhub module if that's the choice you want to make. Any steer would be good as I'm eager to get this change in as I need it like last week :D, any steer would be great since, especially on what topologies this might support I've added `vhub1` as an example assuming there might be more than one.

```hcl
module "alz-connectivity-subscription-001" {
  source   = "Azure/lz-vending/azurerm"
  version  = "3.2.0"
  location = "uksouth"
  subscription_display_name = "alz-sandbox-001"
  ...
  virtual_networks = {
    vnet1 = {
      vwan_security_configuration = {
        secure_internet_traffic = true
        secure_private_traffic  = true
      } // can be used standalone without routing intent
```
You then might want to document that the `virtual_hub` block is best configured where there's a firewall. 
```hcl
module "alz-connectivity-subscription-001" {
  source   = "Azure/lz-vending/azurerm"
  version  = "3.2.0"
  location = "uksouth"
  subscription_display_name = "alz-connectivity-001"
  ...
  virtual_hub = {
        vhub1 = {
        intent_based_routing = {
            virtual_hub_id = virtual_hub.id
            next_hop_firewalls =  firewall.id
           }
      }
 }
```

**Comment by b0bu** [comment]
I've pushed the skeleton of the idea with a bit of placeholder so that we can shape the idea. Happy to adjust in any way that suites your design. I've already started working public and private next hop conditionals etc 

I'll wait for your feed back on the proposed interface.

**Comment by matt-FFFFFF** [comment]
Thanks @b0bu,

We are in the early stages of developing a dedicated vwan module. It would seem that routing intent is a better fit for that module but will leave this open for now

**Comment by b0bu** [comment]
@matt-FFFFFF

I suggest you publish a roadmap if you're developing features in silo that the community can't get involved in. I see no mention of it in the developers.md or PR template or any open branch. If I've missed it in the docs can you link me to it?

**Comment by matt-FFFFFF** [comment]
Hey @b0bu,

Thanks for reaching out.

We should do a better job of publishing our backlog, you're right. We also really do value the contributions made by the community and we are trying to be good open source custodians.

The vwan module decision was very recent, although it had been on our backlog for some time.

To provide some insight into the workings of our team: We have to use an internal backlog, as some of the details in there reference information that has not yet been publicly announced. We use Azure DevOps for this.

We do recognise the need to publish a public facing backlog, though it's a challenge to keep things in sync.

Since all of our modules and projects are in dedicated repos, we need a way of publishing our roadmap that isn't tied to a single repository. GitHub projects seems the right tool for this.

We will work out a way of publishing a public backlog that the community can review, and link to it from our repos.

Sorry this is frustrating. We are working to get better!

/cc @jtracey93 @paulgrimley @JefferyMitchell

**Comment by matt-FFFFFF** [comment]
@b0bu We have created a public roadmap. Hopefully this is useful:

https://aka.ms/alz/roadmap

**Pull request closed without merging**
