### PR TITLE
fix: subscription management group association drift

### PR DESCRIPTION
**Pull request by luke-taylor**
# Overview/summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. fixes #000

### Breaking changes

1. *Replace me*

## Testing evidence

Please provide testing evidence to show that your Pull Request works/fixes as described and documented above.

## As part of this pull request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [ ] Run and `make fmt` & `make docs` to format your code and update documentation.
- [ ] Created unit and deployment tests and provided evidence.
- [ ] Updated relevant and associated documentation.

### CODE REVIEW

**Comment by matt-FFFFFF** [comment]
LGTM @luke-taylor just need to understand the tests and then we can merge.

Due to requirement to increment AzAPI this will have to be a major release

**Comment by matt-FFFFFF** [comment]
requires #313 to be merged as we're using pull request target

**Comment by matt-FFFFFF** [comment]
@luke-taylor I have updated the main branch now, let's get this in :)

**Comment by luke-taylor** [comment]
Happy if you are @matt-FFFFFF :)

**Review by matt-FFFFFF — APPROVED** [review]
Fantastic work here @luke-taylor 🍾

**Pull request merged**
